### PR TITLE
added HCF/GCD program in Cpp

### PR DESCRIPTION
**Pull request by Jagannath-Dutta**

### CODE REVIEW

**Comment by cyberpvn7** [comment]
star this repo

**Comment by Jagannath-Dutta** [comment]
> star this repo

done

**Comment by Jagannath-Dutta** [comment]
> star this repo

why is this repo showing not accepted in hacktoberfest profile?

**Comment by cyberpvn7** [comment]
@Jagannath-Dutta It takes 15min atleast or 1day max

**Comment by Jagannath-Dutta** [comment]
> @Jagannath-Dutta It takes 15min atleast or 1day max

okk

**Pull request merged**
