### PR TITLE
Create Krishnangshu Paul

### PR DESCRIPTION
**Pull request by Krish-Paul**
C++ program to create numbers pyramid

### CODE REVIEW

**Comment by Krish-Paul** [comment]
Please tell me the reason for not merging this. What changes do i need to make

**Comment by cyberpvn7** [comment]
@Krish-Paul thanks for contributing.
and also star this repo

**Comment by Krish-Paul** [comment]
Thank you for your response. I've received a mail for the merge (PR#38) but
in the hacktoberfest profile it is showing NOT ACCEPTED
Could you kindly guide me through this?

Thanking you,
Krishnangshu Paul.

**Comment by cyberpvn7** [comment]
It will update after 15min I think

**Pull request merged**
